### ISSUE TITLE
where is the revolt bot code?

### ISSUE THREAD

**Issue by ErrorOliver** [ktwrd/XeniaBot#12]
"note: xenia is now in maintence mode. only bug fixes will be applied and there will be no new features. [explanation](https://xenia.kate.pet/posts/revolt-edition-update/)"
where is the revolt bot code?

**Comment by ktwrd** [comment]
Source code for the Revolt bot can be found in the [RevSharp Repository](https://github.com/ktwrd/revsharp/) under all projects starting with `RevSharp.Xenia`
